language: go
go:
    - "1.11.x"

sudo: false

env:
    - GO111MODULE="on"

before_install:
    - go get github.com/mattn/goveralls

script:
    - ./coverageTest.sh

after_success:
    - goveralls -coverprofile=coverage.txt -service=travis-ci
